date.timezone=UTC
expose_php=Off
memory_limit=512M
max_execution_time=60
max_input_vars=3000
post_max_size=25M
upload_max_filesize=20M
variables_order=EGPCS

opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=${PHP_OPCACHE_VALIDATE_TIMESTAMPS}
opcache.revalidate_freq=0
